apiVersion: v1
kind: Namespce
metadata
   name: k8s-demo
   
-----------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello
  namespace: k8s-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-hello
  template:
    metadata:
      labels:
        app: k8s-hello
    spec:
      containers:
      - name: k8s-hello
        image: hainv/k8s-hello:1.0
        ports:
        - containerPort: 8080
        
-----------------------------------

apiVersion: v1
kind: Service
metadata:
  name: k8s-hello
  namespace: k8s-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: k8s-hello
    
